ElliottEvansApp/Controllers/JobApplicationsController.cs
using ElliottEvansApp.Data;
using ElliottEvansApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace ElliottEvansApp.Controllers
{
    public class JobApplicationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHost;

        public JobApplicationsController(ApplicationDbContext context, IWebHostEnvironment webHost)
        {
            _context = context;
            _webHost = webHost;
        }

        public async Task<IActionResult> JobApplications(string sortOrder)
        {

            var jobApplications = await _context.JobApplicationsTrackers.ToListAsync();
            ViewData["CompanySortParam"] = String.IsNullOrEmpty(sortOrder) ? "company_desc" : "";
            ViewData["ClosingDateSortParam"] = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            ViewData["StatusSortParam"] = String.IsNullOrEmpty(sortOrder) ? "status_desc" : "";

            //Sorting logic
            switch (sortOrder)
            {
                case "company_desc":
                    jobApplications = jobApplications.OrderByDescending(e => e.CompanyName).ToList();
                    break;
                case "status_desc":
                    jobApplications = jobApplications.OrderByDescending(e => e.Status).ToList();
                    break;
                case "date_asc":
                    jobApplications = jobApplications.OrderBy(e => e.ClosingDate).ToList();
                    break;
                default:
                    jobApplications = jobApplications.OrderBy(e => e.CompanyName).ToList();
                    break;

            } 

            return View(jobApplications);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(JobApplicationsTracker jobApplication, IFormFile? file)
        {
            if (file != null && file.Length > 0)
            {
                // Check if the file size exceeds 300KB
                if (file.Length > 600 * 1024)
                {
                    ModelState.AddModelError("JobSpecification", "File size exceeds the 600KB limit.");
                    return View(jobApplication);
                }

                string uploadsFolder = Path.Combine(_webHost.WebRootPath, "uploads/JobSpecifications");
                string fileName = Path.GetFileName(file.FileName);
                string fileSavePath = Path.Combine(uploadsFolder, fileName);

                using (FileStream stream = new FileStream(fileSavePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                // Store the file path in the JobSpecification property
                jobApplication.JobSpecification = Path.Combine("uploads/JobSpecifications", fileName);
            }
            else
            {
                // Optionally, you can set a default value or leave it as null
                jobApplication.JobSpecification = null;
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(jobApplication);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(JobApplications));
                }
                catch (Exception ex)
                {
                    // Log the exception (you can use a logging framework here)
                    Console.WriteLine(ex.Message);
                }
            }
            else
            {
                // Log the validation errors
                foreach (var state in ModelState)
                {
                    foreach (var error in state.Value.Errors)
                    {
                        Console.WriteLine($"Property: {state.Key}, Error: {error.ErrorMessage}");
                    }
                }
            }

            return View(jobApplication);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            JobApplicationsTracker jobApplication = _context.JobApplicationsTrackers.Find(id);
            if (jobApplication == null)
            {
                return RedirectToAction(nameof(JobApplications));
            }
            else
            {
                _context.JobApplicationsTrackers.Remove(jobApplication);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(JobApplications));
        }

        public IActionResult Edit(int id)
        {
            JobApplicationsTracker jobApplication = _context.JobApplicationsTrackers.Find(id);
            return View(jobApplication);
        }

        [HttpPost]
        public IActionResult Edit(JobApplicationsTracker jobApplication, IFormFile? file)
        {
            
            {
                if (file != null && file.Length > 0)
                {
                    string uploadsFolder = Path.Combine(_webHost.WebRootPath, "uploads/JobSpecifications");
                    string fileName = Path.GetFileName(file.FileName);
                    string fileSavePath = Path.Combine(uploadsFolder, fileName);

                    using (FileStream stream = new FileStream(fileSavePath, FileMode.Create))
                    {
                         file.CopyToAsync(stream);
                    }

                    // Store the file path in the JobSpecification property
                    jobApplication.JobSpecification = Path.Combine("uploads/JobSpecifications", fileName);
                }
                else
                {
                    // Optionally, you can set a default value or leave it as null
                    jobApplication.JobSpecification = null;
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(jobApplication);
                        _context.SaveChangesAsync();
                        return RedirectToAction(nameof(JobApplications));
                    }
                    catch (Exception ex)
                    {
                        // Log the exception (you can use a logging framework here)
                        Console.WriteLine(ex.Message);
                    }
                }
                else
                {
                    // Log the validation errors
                    foreach (var state in ModelState)
                    {
                        foreach (var error in state.Value.Errors)
                        {
                            Console.WriteLine($"Property: {state.Key}, Error: {error.ErrorMessage}");
                        }
                    }
                }

                return View(jobApplication);
            }
        }


        public IActionResult Download(string filePath)
        {
            if (string.IsNullOrEmpty(filePath))
            {
                return NotFound();
            }

            var fullPath = Path.Combine(_webHost.WebRootPath, filePath);
            if (!System.IO.File.Exists(fullPath))
            {
                return NotFound();
            }

            var fileBytes = System.IO.File.ReadAllBytes(fullPath);
            var fileName = Path.GetFileName(fullPath);
            return File(fileBytes, "application/octet-stream", fileName);
        }








    }
}

ElliottEvansApp/Views/JobApplications/Create.cshtml
@model JobApplicationsTracker
@{
    ViewData["Title"] = "Add New Job Application";
}

<div class="container">
    <form asp-action="Create" asp-controller="JobApplications" method="post" enctype="multipart/form-data" >
        <div class="form-group">
            <label asp-for="CompanyName"></label>
            <input asp-for="CompanyName" class="form-control" />
            <span asp-validation-for="CompanyName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Position"></label>
            <input asp-for="Position" class="form-control" />
            <span asp-validation-for="Position" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Location"></label>
            <input asp-for="Location" class="form-control" />
            <span asp-validation-for="Location" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="DateApplied"></label>
            <input asp-for="DateApplied" class="form-control" type="date" />
            <span asp-validation-for="DateApplied" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ClosingDate"></label>
            <input asp-for="ClosingDate" class="form-control" type="date" />
            <span asp-validation-for="ClosingDate" class="text-danger"></span>
        </div>
        <div class="form-group">
	        <label asp-for="ApplicationPlatform"></label>
	        <input asp-for="ApplicationPlatform" class="form-control" />
	        <span asp-validation-for="ApplicationPlatform" class="text-danger"></span>
        </div>
        <div class="form-group">
	        <label asp-for="ApplicationURL"></label>
	        <input asp-for="ApplicationURL" class="form-control" />
	        <span asp-validation-for="ApplicationURL" class="text-danger"></span>
        </div>
        <div class="form-group">
	        <label>Job Specification</label>
	        <input class="form-control" type="file" name="file" />
	        <span asp-validation-for="JobSpecification" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Status"></label>
            <select asp-for="Status" class="form-control">
                <option value="Applied" class="bg-success">Applied</option>
                <option value="Interviewed" class="bg-warning">Interview</option>
                <option value="Rejected" class="bg-danger">Rejected</option>
            </select>
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Notes"></label>
            <input asp-for="Notes" class="form-control" />
            <span asp-validation-for="Notes" class="text-danger"></span>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary mt-2">Add Job Application</button>
        </div>
    </form>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ElliottEvansApp/Views/JobApplications/Edit.cshtml
@model JobApplicationsTracker
@{
    ViewData["Title"] = "Edit Job Application";
}

<div class="container">
	<form asp-action="Edit" asp-controller="JobApplications" method="post" enctype="multipart/form-data">
		<div class="form-group">
			<label asp-for="CompanyName"></label>
			<input asp-for="CompanyName" class="form-control" />
			<span asp-validation-for="CompanyName" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Position"></label>
			<input asp-for="Position" class="form-control" />
			<span asp-validation-for="Position" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Location"></label>
			<input asp-for="Location" class="form-control" />
			<span asp-validation-for="Location" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="DateApplied"></label>
			<input asp-for="DateApplied" class="form-control" type="date" />
			<span asp-validation-for="DateApplied" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="ClosingDate"></label>
			<input asp-for="ClosingDate" class="form-control" type="date" />
			<span asp-validation-for="ClosingDate" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="ApplicationPlatform"></label>
			<input asp-for="ApplicationPlatform" class="form-control" />
			<span asp-validation-for="ApplicationPlatform" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="ApplicationURL"></label>
			<input asp-for="ApplicationURL" class="form-control" />
			<span asp-validation-for="ApplicationURL" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label>Job Specification</label>
			<input class="form-control" type="file" name="file" />
			<span asp-validation-for="JobSpecification" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Status"></label>
			<select asp-for="Status" class="form-control">
				<option value="Applied" class="bg-success">Applied</option>
				<option value="Interviewed" class="bg-warning">Interview</option>
				<option value="Rejected" class="bg-danger">Rejected</option>
			</select>
			<span asp-validation-for="Status" class="text-danger"></span>
		</div>
		<div class="form-group">
			<label asp-for="Notes"></label>
			<input asp-for="Notes" class="form-control" />
			<span asp-validation-for="Notes" class="text-danger"></span>
		</div>
		<div class="text-center">
			<button type="submit" class="btn btn-primary mt-2">Apply Edit</button>
		</div>
	</form>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

ElliottEvansApp/Views/JobApplications/JobApplications.cshtml
@model List<JobApplicationsTracker>
@{
    ViewData["Title"] = "Job Applications";
}

<div class="container ml-n4">
    <div class="text-center mb-3">
        <a asp-action="Create" asp-controller="JobApplications" class="btn btn-primary">Add New Job Application</a>
    </div>

    <div class="table-responsive" style="max-height: 600px; overflow-y: auto;">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
	                <th><a asp-controller="JobApplications" asp-action="JobApplications" asp-route-sortOrder=@ViewData["CompanySortParam"]>Company</a></th>
                    <th>Job Title</th>
                    <th>Location</th>
                    <th>Date Applied</th>
                    <th><a asp-controller="JobApplications" asp-action="JobApplications" asp-route-sortOrder="@ViewData["ClosingDateSortParam"]">Closing Date</a></th>
                    <th>Application Platform</th>
                    <th>Job Specification</th>
                    <th>Application URL</th>
                    <th><a asp-controller="JobApplications" asp-action="JobApplications" asp-route-sortOrder="@ViewData["StatusSortParam"]">Status</a></th>
                    <th>Notes</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Any())
                {
                    @foreach (var jobApplication in Model)
                    {
                        var rowClass = "";
                        if (jobApplication.Status == "Applied")
                        {
                            rowClass = "table-success";
                        }
                        else if (jobApplication.Status == "Interview")
                        {
                            rowClass = "table-warning";
                        }
                        else if (jobApplication.Status == "Rejected")
                        {
                            rowClass = "table-danger";
                        }
                        <tr class="@rowClass">
                            <td>@jobApplication.CompanyName</td>
                            <td>@jobApplication.Position</td>
                            <td>@jobApplication.Location</td>
                            <td>@jobApplication.DateApplied</td>
                            <td>@jobApplication.ClosingDate</td>
                            <td>@jobApplication.ApplicationPlatform</td>
                            <td>
                                @if (!string.IsNullOrEmpty(jobApplication.JobSpecification) && jobApplication.JobSpecification != "No file uploaded")
                                {
                                    <a asp-action="Download" asp-controller="JobApplications" asp-route-filePath="@jobApplication.JobSpecification">Download</a>
                                }
                                else
                                {
                                    <span>No file uploaded</span>
                                }
                            </td>
                            <td>
                                @if (!string.IsNullOrEmpty(jobApplication.ApplicationURL))
                                {
                                    <a href="@jobApplication.ApplicationURL" target="_blank">Link</a>
                                }
                                else
                                {
                                    <span>No URL</span>
                                }
                            </td>
                            <td>@jobApplication.Status</td>
                            <td>@jobApplication.Notes</td>
                            <td>
                                <form asp-action="Delete" asp-controller="JobApplications" method="post" style="display:inline;">
                                    <input type="hidden" name="id" value="@jobApplication.Id" />
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="JobApplications" asp-route-id="@jobApplication.Id" class="btn btn-warning">Edit</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="11">No job applications found</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>